### PR TITLE
Add WebUSB support

### PR DESCRIPTION
**Pull request by jraoult**
#### What does this PR do?
It refactors the USB access code to enable the user to pick the runtime implementation they need.
So now this library can be used equally in Node or the Web platform. Disclaimer: Only the _Blink_ like browsers are supported because it requires WebUSB and WebHID (as of today still behind a flag: cf. chrome://flags/#enable-experimental-web-platform-features).

Because the Web version of the USB api's are asynchronous by design I had to introduce an `init` phase. So for example, to start the node version we should now do:

```ts
// web would be new MaschineMk3(createWebHidAdapter, createWebUsbAdapter)
const mk3 = new MaschineMk3(createNodeHidAdapter, createNodeUsbAdapter)
await mk3.init()
```

#### How should this be tested by the reviewer?
I reused the test app code for the mk3 and created an examples folder with bot boostraps snippets (Node and Web). They can be respectively run with:

```bash
npm run example:maschinemk3:node
```
and (the web version runs parcel bundler and you can then go to http://localhost:1234)
```bash
npm run example:maschinemk3:web
```
They should deliver the same results

#### What are the relevant tickets?
https://github.com/asutherland/node-traktor-f1/issues/2

### CODE REVIEW

**Comment by jraoult** [comment]
@asutherland:

> I noticed when running the demos that only the first button in the group buttons (8) and pads (16) was lit up.

very goo catch and thanks. I ran the demo and realised that by hitting a pad and/or a group button all the LEDs would lit up. I didn't read the code thoroughly enough so I assumed the behaviour was expected 🤦‍♂️:

<div align="center">



</div>

As you might have notice, I removed a call to `setImmediate` (https://github.com/asutherland/ni-controllers-lib/pull/5/files#diff-f930769ddd5f37535e6f43fcef7d0666L255) which has very different scheduling property than `Promise` (the former spawns a macro task, not the latter). I was expecting issue there but my (sub-optimal, we know that now 😉) testing didn't reveal anything. I initially removed `setImmediate` because it is not natively supported by Chrome. I just put it back and it works, so I just added a macro-task shim for Chrome support.

Now, just my thoughts, nothing urgent: moving forward, we could have all the LDS's `setXXX` methods to be explicitly asynchronous (so we ask people to await them) but I feel it would be detrimental to the DevX. We could also have a public API to let the user decided when to send the prepared buffer. The user could pile up instructions (that would just build the buffer content) and then explicitly decided when to "commit", and only this "commit" would need to be _awaited_.

**Comment by jraoult** [comment]
>  [...] but if you tested on Windows and have any ideas, I'd be interested

😬 I don't even have a Windows machine but I can try with my Parallel Desktop VM and see. If we can't get it work I'll add a disclaimer in the README about Windows.

**Comment by asutherland** [comment]
The change to schedule a task again (pedantic hat on: there's no such thing as a macrotask, just tasks and microtasks) isn't sufficient if there are async writes that allow other code that could call buffer mutating functions between the buffer contents being snapshotted and when the write asynchronously completes and the dirty flag is cleared.  I think the code in https://github.com/asutherland/ni-controllers-lib/commit/6ce6a14e558445bceb87df71935b89d80350b250 probably expresses this better than prose.

In the above commit I went with a microtask instead of a task this time because web browser main event loops can get very busy, especially when there's other content JS doing long-running things, so I think it's preferable to perform the flush during the microtask checkpoint of the task that initiated the mutations.

I agree that having every mutation be async would probably impact ergonomics.  Similarly agreed that specifying the flush mechanism for the device at creation time would make sense, though.  The default could be 'auto' and would be similar to what's in https://github.com/asutherland/ni-controllers-lib/commit/6ce6a14e558445bceb87df71935b89d80350b250 (delay the flush with a microtask, then auto re-flushing each time the write completes and finds things are still dirty), with 'manual' allowing `flushOutput()` or similar to be called on the device, which would be explicitly async.

> I don't even have a Windows machine but I can try with my Parallel Desktop VM and see. If we can't get it work I'll add a disclaimer in the README about Windows.

I can handle the attempted windows testing / googling stackoverflow then.  I just didn't want to duplicate any effort you might have already made.  Although using USB from VMs has usually gone a lot better than I expected, it seems like it could be an even bigger hassle than trying to do it from Windows running on the bare metal.

**Comment by jraoult** [comment]
> In the above commit I went with a microtask instead of a task this time because web browser main event loops can get very busy, especially when there's other content JS doing long-running things, so I think it's preferable to perform the flush during the microtask checkpoint of the task that initiated the mutations.

I see... makes sense. So let me rollback the addition of the macrotask lib and cherry pick https://github.com/asutherland/ni-controllers-lib/commit/6ce6a14e558445bceb87df71935b89d80350b250 since it seems you put way more thoughts than me into it 😉 I like the idea around the `flushOutput()` mechanic, we try to treat this in another PR later on.

**Comment by jraoult** [comment]
@asutherland done

**Comment by asutherland** [comment]
Awesome!  Feel free to hit the merge button whenever suits you.

My landing process is colored by the Mozilla process, which is generally that if someone with commit privileges gets a positive review, they can land the changes themselves since there may be nits they may choose to respond to or not, etc.  It's always their choice to re-request review if they make additional changes they'd like additional feedback on.  I'm open to other landing processes, however, if you'd prefer something else.

(And of course pull requests for non-committers would need to be landed by the reviewer/a committer.)

**Comment by jraoult** [comment]
@asutherland sounds good to me. I also think it suits the (low) risk profile of this library and our async workflow pretty well.

**Pull request merged**
